branch-defaults:
  default:
    environment: postgresSample
  master:
    environment: syllin-env
    group_suffix: null
environment-defaults:
  flask-sample-db-env:
    branch: null
    repository: null
global:
  application_name: flask-tutorial
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 2.7
  default_region: us-west-2
  profile: eb-cli
  repository: null
  sc: git
