"""empty message

Revision ID: 7abebcc40d47
Revises: 
Create Date: 2017-03-24 16:20:30.012355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7abebcc40d47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('does_migrate_work', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'does_migrate_work')
    # ### end Alembic commands ###
