"""empty message

Revision ID: a72fd3d83ccc
Revises: 7abebcc40d47
Create Date: 2017-03-24 16:21:14.572847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a72fd3d83ccc'
down_revision = '7abebcc40d47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'does_migrate_work')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('does_migrate_work', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
